language: node_js
node_js:
  - 4.1
env:
  - CXX=g++-4.8
  global:
    - secure: N/yV6FNB4bOhqk5AgGTMylbHTk/2uZK/kfOmIiDRhK6eIeuDcyb/KyasAeFztnzRxbjeLx1pCimSafthLbL4VxP1MtNag/qYwg/58tQ89guuvkFuAdYAVk28Ub6giW6mAQZyfzehrwOOVZeMhl7w4Kg9UNC3Y4iGF746pkworGM=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_install:
  ############
  ## Need special configuration to enable Chrome support for KarmaJS
  ## http://stackoverflow.com/a/25661593/633438
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  ############
  - npm install -g gulp
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
  - jspm install